language: node_js
node_js:
  - '8'
before_script:
  - npm test
  - npm run build
before_deploy: "echo 'ready?'"
deploy:
  provider: firebase
  token:
    secure: "1/D-HixUt163_k4iHgs5a1ANuV8yOJ2S6tbIPAiPdmcXM"