language: node_js
node_js:
  - '8'
branches:
  only:
  - master
before_install:
  - npm install -g firebase-tools
install:
  - npm install
  - npm run build
  - "echo 'creating test.json'"
  - ls
  - echo "{apps:[{name:\"$FIREBASE_TOKEN\",script:\"./cms/bin/www\",watch:false}]}" > process.json
  - cat process.json
before_deploy: "echo 'ready?'"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "userddata"
  skip_cleanup: true
after_success:
  - firebase deploy --project userddata --only hosting --token $FIREBASE_TOKEN