language: node_js
node_js:
  - '8'
branches:
  only:
  - master
before_install:
  - npm install -g firebase-tools
install:
  - npm install
  - npm run build
  - "echo 'creating test.json'"
  - ls
  - echo "some file content" > test.json
  - ls
before_deploy: "echo 'ready?'"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "userddata"
  skip_cleanup: true
after_success:
  - firebase deploy --project userddata --only hosting --token $FIREBASE_TOKEN