language: node_js
node_js:
  - '8'
branches:
  only:
  - master
before_install:
  - npm install -g firebase-tools
install:
  - npm install
  - npm run build
  - "echo 'what is going to happen'"
  - ls
before_deploy: "echo 'ready?'"
deploy:
  provider: firebase
  token:
    secure: "1/D-HixUt163_k4iHgs5a1ANuV8yOJ2S6tbIPAiPdmcXM"
  project: "userddata"
  skip_cleanup: true
after_success:
  - firebase deploy --project userddata --only hosting --token $FIREBASE_TOKEN